{% set name = "lensfunpy" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/letmaik/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dbba55c0c5beec93155ef1f92447557ef93caca831d2f180130b4c751582f04c
  patches:
    - 0002_remove_osx_condition.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - cython
    - delocate  # [osx]
    - lensfun <0.3.95
    - numpy
    - pip
    - python
  run:
    - cython
    - {{ pin_compatible('numpy') }}
    - lensfun <0.3.95
    - {{ pin_compatible('lensfun') }}
    - python
    - scipy

test:
  imports:
    - lensfunpy

about:
  home: https://letmaik.github.io/lensfunpy/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: lensfunpy is an easy-to-use Python wrapper for the lensfun library.
  doc_url: https://pypi.org/project/lensfunpy/
  dev_url: https://github.com/letmaik/lensfunpy

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - mwilson8
    - rluria14
    - anthchirp
