{% set name = "lensfunpy" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/letmaik/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b9b2ad055aa1112dca16d565a2c3c4386436f3189d32745882f1d933deca0d07
  patches:
    - 0002_remove_osx_condition.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - cython
    - delocate  # [osx]
    - lensfun <0.3.95
    - numpy
    - pip
    - python
  run:
    - cython
    - {{ pin_compatible('numpy') }}
    - lensfun <0.3.95
    - {{ pin_compatible('lensfun') }}
    - python
    - scipy

test:
  imports:
    - lensfunpy

about:
  home: https://letmaik.github.io/lensfunpy/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: lensfunpy is an easy-to-use Python wrapper for the lensfun library.
  doc_url: https://pypi.org/project/lensfunpy/
  dev_url: https://github.com/letmaik/lensfunpy

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - mwilson8
    - rluria14
    - anthchirp
